children:
  - name: production
  - name: staging
  - name: group_vars
  - name: host_vars
  - name: library
  - name: module_utils
  - name: filter_plugins
  - name: roles
    children:
      - name: common
        children:
          - name: tasks
            children:
              - name: main.yml
          - name: handlers
            children:
              - name: main.yml
          - name: templates
            children:
              - name: ntp.conf.j2
          - name: files
            children:
              - name: bar.txt
              - name: foo.sh
          - name: vars
            children:
              - name: main.yml
          - name: defaults
            children:
              - name: main.yml
          - name: meta
            children:
              - name: main.yml
          - name: library
          - name: module_utils
          - name: lookup_plugins
      - name: webtier
      - name: monitoring
      - name: fooapp
  - name: site.yml
  - name: webservers.yml
  - name: dbservers.yml
  - name: .gitignore
  - name: README.md
  - name: LICENSE
  - name: requirements.txt
  - name: ansible.cfg
  - name: group_vars
    children:
      - name: group1.yml
      - name: group2.yml
  - name: host_vars
    children:
      - name: hostname1.yml
      - name: hostname2.yml
