children:
  - name: README.md
  - name: environments
    children:
      - name: dev
      - name: prod
  - name: main.tf
  - name: modules
  - name: outputs.tf
  - name: provider.tf
  - name: terraform.tfvars
  - name: tests
  - name: variables.tf
