directories:
  - name: "modules"
  - name: "environments"
    children:
      - name: "dev"
      - name: "prod"

files:
  - name: "main.tf"
  - name: "variables.tf"
  - name: "outputs.tf"
  - name: "README.md"
  - name: ".gitignore"
